#ifndef __CONSTANTS_H_
#define __CONSTANTS_H_

// THIS IS THE LIST OF THE CONSTANTS (NOT PARAMETERS!)
// THIS VALUES SHOULD NEVER CHANGE, NO MATTER WHAT

#define FRAME_SIZE 25
#define BINOMIAL_N 14

#define RNG_CQI 0
#define RNG_SERVICE_DEMAND 1
#define RNG_RECIPIENT 2
#define RNG_INTERARRIVAL 3

#define MIN_CQI 1
#define MAX_CQI 15

#define MIN_SERVICE_DEMAND 1
#define MAX_SERVICE_DEMAND 75

#define MIN_USERS 1

#define MSG_PKT_TIMER 0
#define MSG_RR_TIMER  1

#endif
