#ifndef __CONSTANTS_H_
#define __CONSTANTS_H_

// THIS IS THE LIST OF THE CONSTANTS (NOT PARAMETERS!)
// THIS VALUES SHOULD NEVER CHANGE, NO MATTER WHAT

#define FRAME_SIZE 25

#define SEED_CQI 1
#define SEED_SERVICE_DEMAND 2
#define SEED_RECIPIENT 3

#define MIN_CQI 1
#define MAX_CQI 15

#define MIN_SERVICE_DEMAND 1
#define MAX_SERVICE_DEMAND 75

#define MIN_USERS 1

#endif
