//
// Generated file, do not edit! Created by nedtool 5.5 from Frame.msg.
//

#ifndef __FRAME_M_H
#define __FRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ResourceBlock.h"	
// }}

/**
 * Class generated from <tt>Frame.msg:7</tt> by nedtool.
 * <pre>
 * message Frame
 * {
 *     ResourceBlock RBs[25];
 * }
 * </pre>
 */
class Frame : public ::omnetpp::cMessage
{
  protected:
    ResourceBlock RBs[25];

  private:
    void copy(const Frame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Frame&);

  public:
    Frame(const char *name=nullptr, short kind=0);
    Frame(const Frame& other);
    virtual ~Frame();
    Frame& operator=(const Frame& other);
    virtual Frame *dup() const override {return new Frame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getRBsArraySize() const;
    virtual ResourceBlock& getRBs(unsigned int k);
    virtual const ResourceBlock& getRBs(unsigned int k) const {return const_cast<Frame*>(this)->getRBs(k);}
    virtual void setRBs(unsigned int k, const ResourceBlock& RBs);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Frame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Frame& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FRAME_M_H

