//
// Generated file, do not edit! Created by nedtool 5.5 from PacketCQI.msg.
//

#ifndef __PACKETCQI_M_H
#define __PACKETCQI_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PacketCQI.msg:2</tt> by nedtool.
 * <pre>
 * message PacketCQI
 * {
 *     //  int senderID;
 *     int userID;
 *     int cqi;
 * }
 * </pre>
 */
class PacketCQI : public ::omnetpp::cMessage
{
  protected:
    int userID;
    int cqi;

  private:
    void copy(const PacketCQI& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketCQI&);

  public:
    PacketCQI(const char *name=nullptr, short kind=0);
    PacketCQI(const PacketCQI& other);
    virtual ~PacketCQI();
    PacketCQI& operator=(const PacketCQI& other);
    virtual PacketCQI *dup() const override {return new PacketCQI(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getUserID() const;
    virtual void setUserID(int userID);
    virtual int getCqi() const;
    virtual void setCqi(int cqi);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketCQI& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketCQI& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKETCQI_M_H

