//
// Generated file, do not edit! Created by nedtool 5.5 from PacketTimer.msg.
//

#ifndef __PACKETTIMER_M_H
#define __PACKETTIMER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PacketTimer.msg:1</tt> by nedtool.
 * <pre>
 * message PacketTimer
 * {
 *     int userId;
 * }
 * </pre>
 */
class PacketTimer : public ::omnetpp::cMessage
{
  protected:
    int userId;

  private:
    void copy(const PacketTimer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketTimer&);

  public:
    PacketTimer(const char *name=nullptr, short kind=0);
    PacketTimer(const PacketTimer& other);
    virtual ~PacketTimer();
    PacketTimer& operator=(const PacketTimer& other);
    virtual PacketTimer *dup() const override {return new PacketTimer(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getUserId() const;
    virtual void setUserId(int userId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketTimer& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketTimer& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKETTIMER_M_H

